anyio==4.3.0
appdirs==1.4.4
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.1
async-lru==2.0.4
attrs==21.4.0
autograd==1.6.2
autoray==0.6.8
Babel==2.14.0
beautifulsoup4==4.12.3
bleach==6.1.0
cachetools==5.3.2
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
cirq==1.3.0
cirq-aqt==1.3.0
cirq-core==1.3.0
cirq-ft==1.3.0
cirq-google==1.3.0
cirq-ionq==1.3.0
cirq-pasqal==1.3.0
cirq-rigetti==1.3.0
cirq-web==1.3.0
comm==0.2.1
contourpy==1.2.0
cycler==0.12.1
debugpy==1.8.1
decorator==5.1.1
defusedxml==0.7.1
Deprecated==1.2.14
dill==0.3.8
docplex==2.25.236
duet==0.2.9
executing==2.0.1
fastdtw==0.3.4
fastjsonschema==2.19.1
fonttools==4.49.0
fqdn==1.5.1
future==1.0.0
google-api-core==2.17.1
google-auth==2.28.1
googleapis-common-protos==1.62.0
grpcio==1.62.0
grpcio-status==1.62.0
h11==0.14.0
h5py==3.10.0
httpcore==0.16.3
httpx==0.23.3
idna==3.6
ipykernel==6.29.2
ipython==8.22.1
ipywidgets==8.1.2
iso8601==1.1.0
isoduration==20.11.0
jedi==0.19.1
Jinja2==3.1.3
joblib==1.3.2
json5==0.9.17
jsonpointer==2.4
jsonschema==4.17.3
jsonschema-specifications==2023.12.1
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.9.0
jupyter-lsp==2.2.2
jupyter_client==8.6.0
jupyter_core==5.7.1
jupyter_server==2.12.5
jupyter_server_terminals==0.5.2
jupyterlab==4.1.2
jupyterlab_pygments==0.3.0
jupyterlab_server==2.25.3
jupyterlab_widgets==3.0.10
kiwisolver==1.4.5
lark==0.11.3
MarkupSafe==2.1.5
matplotlib==3.8.3
matplotlib-inline==0.1.6
mistune==3.0.2
mpmath==1.3.0
msgpack==1.0.7
nbclient==0.9.0
nbconvert==7.16.1
nbformat==5.9.2
nest-asyncio==1.6.0
networkx==3.2.1
notebook==7.1.0
notebook_shim==0.2.4
numpy==1.26.4
overrides==7.7.0
packaging==23.2
pandas==2.2.1
pandocfilters==1.5.1
parso==0.8.3
pbr==6.0.0
PennyLane==0.34.0
PennyLane-Lightning==0.34.0
pexpect==4.9.0
pillow==10.2.0
platformdirs==4.2.0
plotly==5.19.0
ply==3.11
prometheus_client==0.20.0
prompt-toolkit==3.0.43
proto-plus==1.23.0
protobuf==4.25.3
psutil==5.9.8
ptyprocess==0.7.0
pure-eval==0.2.2
pyasn1==0.5.1
pyasn1-modules==0.3.0
pycparser==2.21
pydantic==1.10.14
Pygments==2.17.2
PyJWT==2.8.0
pyparsing==3.1.1
pyquil==3.5.4
pyrsistent==0.20.0
python-dateutil==2.8.2
python-json-logger==2.0.7
python-rapidjson==1.14
pytz==2024.1
PyYAML==6.0.1
pyzmq==25.1.2
qcs-api-client==0.21.6
qiskit==0.45.2
qiskit-aer==0.13.2
qiskit-algorithms==0.3.0
qiskit-machine-learning==0.7.1
qiskit-nature==0.7.2
qiskit-optimization==0.6.0
qiskit-terra==0.45.2
qtconsole==5.5.1
QtPy==2.4.1
referencing==0.33.0
requests==2.31.0
retrying==1.3.4
rfc3339==6.2
rfc3339-validator==0.1.4
rfc3986==1.5.0
rfc3986-validator==0.1.1
rpcq==3.11.0
rpds-py==0.18.0
rsa==4.9
ruamel.yaml==0.18.6
ruamel.yaml.clib==0.2.8
rustworkx==0.14.1
scikit-learn==1.4.1.post1
scipy==1.12.0
semantic-version==2.10.0
Send2Trash==1.8.2
six==1.16.0
sniffio==1.3.1
sortedcontainers==2.4.0
soupsieve==2.5
stack-data==0.6.3
stevedore==5.2.0
symengine==0.11.0
sympy==1.12
tenacity==8.2.3
terminado==0.18.0
threadpoolctl==3.3.0
tinycss2==1.2.1
toml==0.10.2
tornado==6.4
tqdm==4.66.2
traitlets==5.14.1
types-Deprecated==1.2.9.20240106
types-python-dateutil==2.8.19.20240106
types-retry==0.9.9.4
typing_extensions==4.10.0
tzdata==2024.1
uri-template==1.3.0
urllib3==2.2.1
wcwidth==0.2.13
webcolors==1.13
webencodings==0.5.1
websocket-client==1.7.0
widgetsnbextension==4.0.10
wrapt==1.16.0
